#!/usr/bin/env python3
"""Scaffold/refresh a knowledge-base INDEX.md and per-area _manifest.md stubs.

After ``ingest.py`` has mirrored the corpus into a KB directory, this builds
the two navigation artifacts that make the KB agent-searchable:

  * ``INDEX.md`` — one row per converted document: relative path, the native
    requirement-ID *families* detected in it (by prefix), and how many IDs were
    found. Grouped by top-level area.
  * ``<area>/_manifest.md`` — a per-area stub recording the conversion method
    and a "quality caveats" checklist to fill in (degraded OCR, bilingual/RTL).
    Existing manifests are never overwritten.

Requirement-ID detection is regex-driven and domain-agnostic. The defaults
recognise three common shapes; override or extend them with ``--id-pattern``:

    multi-dashed   ABC-DE-FGH-001   ( ORG-CM-ACA-BR001 )
    underscore     AB_123           ( DC_007 )
    dotted         AB-CD-EF-1.2      ( FCS-CMD-PRC-1.1 )

The "family" reported for an ID is its leading alpha token (the part before the
first ``-`` or ``_``), so ``ORG-CM-ACA-BR001`` and ``DC_007`` report families
``ORG`` and ``DC``. This needs no domain knowledge baked in.

    gen_index.py KB_DIR [--write-manifests]
    gen_index.py KB_DIR --check          # verify the KB before bootstrap (stage 1 -> 2 gate)
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

# name -> regex. Kept generic; extend with --id-pattern NAME=REGEX.
DEFAULT_ID_PATTERNS: dict[str, str] = {
    "multi-dashed": r"\b[A-Z][A-Z0-9]*(?:-[A-Z0-9]+){2,}\b",
    "underscore": r"\b[A-Z]{2,}_\d+\b",
    "dotted": r"\b[A-Z]{2,}(?:-[A-Z0-9]+)+\.\d+(?:\.\d+)*\b",
}

INDEX_NAME = "INDEX.md"
MANIFEST_NAME = "_manifest.md"
SOURCE_PREFIX_PLAIN = "> Source:"


def family_of(identifier: str) -> str:
    """Leading alpha token: 'ORG-CM-ACA-BR001' -> 'ORG', 'DC_007' -> 'DC'."""
    return re.split(r"[-_.]", identifier, maxsplit=1)[0]


def detect_ids(text: str, regexes: list[re.Pattern[str]]) -> tuple[set[str], int]:
    """Return (set of families, total ID matches) for one document."""
    families: set[str] = set()
    total = 0
    for rx in regexes:
        for match in rx.findall(text):
            total += 1
            families.add(family_of(match))
    return families, total


def build_index(kb_dir: Path, regexes: list[re.Pattern[str]]) -> str:
    docs: list[tuple[str, set[str], int]] = []
    family_totals: Counter[str] = Counter()

    for md in sorted(kb_dir.rglob("*.md")):
        if md.name in (INDEX_NAME, MANIFEST_NAME):
            continue
        rel = md.relative_to(kb_dir).as_posix()
        text = md.read_text(encoding="utf-8", errors="replace")
        families, total = detect_ids(text, regexes)
        docs.append((rel, families, total))
        for fam in families:
            family_totals[fam] += 1

    # Group rows by top-level area (first path segment).
    by_area: dict[str, list[tuple[str, set[str], int]]] = {}
    for rel, families, total in docs:
        area = rel.split("/", 1)[0] if "/" in rel else "(root)"
        by_area.setdefault(area, []).append((rel, families, total))

    lines: list[str] = []
    lines.append("# Knowledge Base Index")
    lines.append("")
    lines.append(
        f"> Generated by gen_index.py. {len(docs)} document(s) across "
        f"{len(by_area)} area(s). Native requirement IDs are preserved verbatim "
        f"in each document as grep targets; this index lists which ID families "
        f"appear where."
    )
    lines.append("")

    if family_totals:
        lines.append("## ID families detected")
        lines.append("")
        lines.append("| Family | Documents |")
        lines.append("| --- | --- |")
        for fam, n in sorted(family_totals.items()):
            lines.append(f"| {fam} | {n} |")
        lines.append("")

    lines.append("## Documents")
    lines.append("")
    for area in sorted(by_area):
        lines.append(f"### {area}")
        lines.append("")
        lines.append("| Document | ID families | IDs found |")
        lines.append("| --- | --- | --- |")
        for rel, families, total in sorted(by_area[area]):
            fam_str = ", ".join(sorted(families)) if families else "-"
            lines.append(f"| {rel} | {fam_str} | {total} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def check_kb(kb_dir: Path, regexes: list[re.Pattern[str]]) -> int:
    """Assert the KB satisfies the conventions the method depends on.

    Hard failures (exit non-zero):
      * a converted .md with no ``> Source:`` provenance line.
    Soft warnings (reported, do NOT fail the gate):
      * a .md in which no native requirement-ID family was detected.
      * a _manifest.md still carrying the unfilled generated stub.
    """
    missing_source: list[str] = []
    no_ids: list[str] = []
    unfilled_manifests: list[str] = []

    for md in sorted(kb_dir.rglob("*.md")):
        rel = md.relative_to(kb_dir).as_posix()
        text = md.read_text(encoding="utf-8", errors="replace")
        if md.name == INDEX_NAME:
            continue
        if md.name == MANIFEST_NAME:
            if "Generated stub" in text and "- [ ]" in text:
                unfilled_manifests.append(rel)
            continue
        head = "\n".join(text.splitlines()[:5])
        if SOURCE_PREFIX_PLAIN not in head:
            missing_source.append(rel)
        _families, total = detect_ids(text, regexes)
        if total == 0:
            no_ids.append(rel)

    def _report(label: str, items: list[str]) -> None:
        if not items:
            return
        print(f"\n{label} ({len(items)}):", file=sys.stderr)
        for item in items:
            print(f"  - {item}", file=sys.stderr)

    _report("FAIL: no `> Source:` provenance line", missing_source)
    _report("WARN: no native requirement-ID family detected", no_ids)
    _report("WARN: _manifest.md quality caveats still unfilled", unfilled_manifests)

    if missing_source:
        print(
            f"\ncheck: FAILED — {len(missing_source)} file(s) missing a `> Source:` line. "
            "Re-run ingest.py; do NOT proceed to bootstrap on a malformed KB.",
            file=sys.stderr,
        )
        return 1
    print(
        "\ncheck: OK — every converted doc has a `> Source:` line. "
        f"({len(no_ids)} file(s) with no detected ID family, "
        f"{len(unfilled_manifests)} manifest(s) still to curate — review the warnings above.)",
        file=sys.stderr,
    )
    return 0


def manifest_stub(area: str, doc_count: int) -> str:
    return (
        f"# {area} — conversion manifest\n"
        "\n"
        "> Generated stub. Record how each source format was converted and fill in\n"
        "> the quality caveats below. Delete a checkbox line once verified.\n"
        "\n"
        f"Documents in this area: {doc_count}\n"
        "\n"
        "## Conversion method\n"
        "\n"
        "| Source format | Converter |\n"
        "| --- | --- |\n"
        "| .docx / .pptx / .pdf / .html | markitdown (pipx, Python 3.13) |\n"
        "| .xlsx / .xls | extractors/xlsx_to_md.py (openpyxl) |\n"
        "| .vsdx | extractors/vsdx_to_md.py |\n"
        "| .md / .txt | passthrough (e.g. flow step text) |\n"
        "\n"
        "## Quality caveats\n"
        "\n"
        "- [ ] OCR'd scans: verify numeric/clinical values against the canonical source.\n"
        "- [ ] Bilingual content (e.g. Arabic): confirm RTL text order survived conversion.\n"
        "- [ ] Process flows: a rendered .png/.pdf is kept alongside the .md (dual-capture).\n"
        "- [ ] Excluded/superseded originals (*-OLD*, *Old.docx) were not converted.\n"
        "- [ ] Duplicate documents resolved to a single canonical copy.\n"
    )


def write_manifests(kb_dir: Path) -> list[Path]:
    """Write a _manifest.md stub into each top-level area dir that lacks one."""
    written: list[Path] = []
    areas: dict[str, int] = {}
    for md in kb_dir.rglob("*.md"):
        if md.name in (INDEX_NAME, MANIFEST_NAME):
            continue
        rel = md.relative_to(kb_dir)
        if len(rel.parts) < 2:
            continue  # root-level doc, no area
        areas[rel.parts[0]] = areas.get(rel.parts[0], 0) + 1

    for area, count in sorted(areas.items()):
        manifest = kb_dir / area / MANIFEST_NAME
        if manifest.exists():
            continue
        manifest.write_text(manifest_stub(area, count), encoding="utf-8")
        written.append(manifest)
    return written


def parse_patterns(extra: list[str] | None) -> list[re.Pattern[str]]:
    patterns = dict(DEFAULT_ID_PATTERNS)
    for spec in extra or []:
        if "=" not in spec:
            raise SystemExit(f"error: --id-pattern must be NAME=REGEX, got: {spec}")
        name, _, regex = spec.partition("=")
        patterns[name.strip()] = regex
    compiled: list[re.Pattern[str]] = []
    for name, regex in patterns.items():
        try:
            compiled.append(re.compile(regex))
        except re.error as exc:
            raise SystemExit(f"error: bad regex for '{name}': {exc}") from exc
    return compiled


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_index.py",
        description="Build INDEX.md and per-area _manifest.md stubs for a KB directory.",
    )
    parser.add_argument("kb_dir", type=Path, help="Knowledge-base directory to index.")
    parser.add_argument(
        "--id-pattern",
        action="append",
        metavar="NAME=REGEX",
        help="Add/override a requirement-ID regex (repeatable).",
    )
    parser.add_argument(
        "--write-manifests",
        action="store_true",
        help="Also write a _manifest.md stub into each area dir that lacks one.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Verify the KB instead of (re)building the index: every .md has a "
            "`> Source:` line, report files with no detected requirement-ID family, "
            "flag unfilled _manifest stubs. Exit non-zero on a missing Source line. "
            "Use as the gate between ingestion (stage 1) and bootstrap (stage 2)."
        ),
    )
    args = parser.parse_args(argv)

    if not args.kb_dir.is_dir():
        print(f"error: not a directory: {args.kb_dir}", file=sys.stderr)
        return 2

    regexes = parse_patterns(args.id_pattern)

    if args.check:
        return check_kb(args.kb_dir, regexes)

    index_text = build_index(args.kb_dir, regexes)
    index_path = args.kb_dir / INDEX_NAME
    index_path.write_text(index_text, encoding="utf-8")
    print(f"wrote {index_path}", file=sys.stderr)

    if args.write_manifests:
        written = write_manifests(args.kb_dir)
        if written:
            for path in written:
                print(f"wrote {path}", file=sys.stderr)
        else:
            print("no new _manifest.md stubs (all areas already have one)",
                  file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
